// Fixture builders for the live-Electron smoke test (issue #35).
//
// These generate throwaway repos in a fresh temp dir per run — never real
// projects — and bind every GodMode role to a FAKE CLI script. No real agent
// CLI (claude/codex/hermes) is ever referenced, and nothing here shells out to
// `gh` or touches the network. Side-effect-free on import: callers invoke the
// builders explicitly (so this file is inert if the test runner ever discovers
// it).
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

/**
 * The recognizable marker the fake agent prints. The smoke asserts this appears
 * in captured PTY output, proving a real role session launched. Kept distinct so
 * it can never be confused with incidental terminal chatter.
 */
export const FAKE_AGENT_MARKER = 'GODMODE_FAKE_AGENT_MARKER';

/**
 * The fake agent CLI. It prints the marker plus its working directory (so the
 * smoke can assert the PTY launched in the OPERATED-PROJECT root, not the app
 * repo), then exits 0. `pwd -P` resolves symlinks so the printed path matches
 * the realpath'd fixture root the test selects (macOS temp dirs live under a
 * /private symlink). It never invokes any real tool.
 */
const FAKE_AGENT_SCRIPT = `#!/bin/sh
# Fake GodMode agent CLI used only by the smoke test. Prints a marker + cwd,
# then exits cleanly. Never calls a real agent or touches the network.
echo "${FAKE_AGENT_MARKER} role=\${GODMODE_FAKE_ROLE:-unknown} cwd=$(pwd -P)"
exit 0
`;

/** The fixture's .agentic/godmode.yaml: distinct display names, all roles fake. */
const FIXTURE_CONFIG_YAML = `# Smoke-test fixture config. Every role is bound to a fake CLI; no real agent.
project:
  name: Fake Operated Project
  default_branch: main

roles:
  head:
    agent: fake-head
    pane: head
    display_name: Fake Head
  builder:
    agent: fake-builder
    pane: builder
    display_name: Fake Builder
  reviewers:
    - id: fake-rev-a
      agent: fake-reviewer-a
      pane: reviewer_a
      display_name: Fake Reviewer A
      role_doc: docs/review/a.md
    - id: fake-rev-b
      agent: fake-reviewer-b
      pane: reviewer_b
      display_name: Fake Reviewer B
      role_doc: docs/review/b.md

agents:
  fake-head:
    adapter: cli
    command: ./fake-agent.sh
    mode: interactive
  fake-builder:
    adapter: cli
    command: ./fake-agent.sh
    mode: interactive
  fake-reviewer-a:
    adapter: cli
    command: ./fake-agent.sh
    mode: oneshot
  fake-reviewer-b:
    adapter: cli
    command: ./fake-agent.sh
    mode: oneshot
`;

/**
 * Create a fresh, realpath'd base temp dir for one smoke run. Realpath matters:
 * macOS `os.tmpdir()` is a symlink (/var → /private/var), and the app resolves
 * the selected project with `path.resolve` (no symlink resolution) while the
 * fake CLI prints `pwd -P` (resolved). Returning the resolved base keeps both
 * sides equal so the operated-project-root assertion is exact.
 */
export function createSmokeBaseDir() {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), 'godmode-smoke-'));
  return fs.realpathSync.native(base);
}

/**
 * Build a valid GodMode harness repo bound to fake CLIs. Writes AGENTS.md +
 * README.md (so harness detection reports `valid`), the fixture config, and the
 * executable fake agent. Returns the absolute repo root.
 */
export function createHarnessRepo(baseDir) {
  const root = path.join(baseDir, 'harness-repo');
  fs.mkdirSync(path.join(root, '.agentic'), { recursive: true });
  fs.mkdirSync(path.join(root, 'docs', 'review'), { recursive: true });

  fs.writeFileSync(
    path.join(root, 'AGENTS.md'),
    '# Fake Operated Project\n\nSmoke-test harness fixture. Not a real project.\n',
  );
  fs.writeFileSync(
    path.join(root, 'README.md'),
    '# Fake Operated Project\n\nGenerated by the GodMode smoke test.\n',
  );
  fs.writeFileSync(path.join(root, 'docs', 'review', 'a.md'), '# Reviewer A role doc (fixture)\n');
  fs.writeFileSync(path.join(root, 'docs', 'review', 'b.md'), '# Reviewer B role doc (fixture)\n');
  fs.writeFileSync(path.join(root, '.agentic', 'godmode.yaml'), FIXTURE_CONFIG_YAML);

  const cli = path.join(root, 'fake-agent.sh');
  fs.writeFileSync(cli, FAKE_AGENT_SCRIPT);
  fs.chmodSync(cli, 0o755);

  return root;
}

/**
 * Build a directory with no harness files at all, so harness detection reports
 * `missing` (the required AGENTS.md + README/spec are both absent). Used to prove
 * the negative branch of project selection.
 */
export function createNonHarnessDir(baseDir) {
  const root = path.join(baseDir, 'not-a-harness');
  fs.mkdirSync(root, { recursive: true });
  fs.writeFileSync(path.join(root, 'notes.txt'), 'Just a plain directory, no GodMode harness.\n');
  return root;
}

/** Recursively remove a smoke base dir, ignoring errors (best-effort cleanup). */
export function cleanupBaseDir(baseDir) {
  try {
    fs.rmSync(baseDir, { recursive: true, force: true });
  } catch {
    // Best-effort: a leftover temp dir is harmless.
  }
}
